Fix EZP-23264: hasParameter() of LegacyConfigResolver causes an error, if the requester parameter does not exist.
> https://jira.ez.no/browse/EZP-23264

An error occurs if you want to check the existence of a specfic parameter, which is not defined.
For example:
```php
$configResolver->hasParameter('parameter_name', 'name_space');
```

Exception message:
> ContextErrorException: Notice: Undefined offset: 1 in
> /path/to/symfony/vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishLegacyBundle/DependencyInjection/Configuration/LegacyConfigResolver.php
> line 151